### ISSUE TITLE
API mismatch

### ISSUE THREAD

**Issue by TonyCanning** [hobinjk/clap-sensor-adapter#1]
Getting this error:

2018-04-27 17:55:13.741 API mismatch for package: clap-sensor-adapter
Current: 2 Supported: 1-1

I'm no coder so I just searched through ~/.mozilla-iot/addons/clap-sensor-adapter/ to see where there could be some conflict.

in package.json i changed the max value:

  "moziot": {
    "api": {
      "min": 1,
      "max": 2 // this was previously set to 1.
},

I haven't a clue if this is the appropriate way to solve the issue but I'm now seeing the adapter.

Hope this maybe helps someone out!

TC

**Comment by hobinjk** [comment]
Thanks for pointing this out! I just pushed an update that should fix the API mismatch. It also includes the Adapter, Device, and Property classes from the proper API level 2 location
