### ISSUE TITLE
Many lines of code are never executed, then what it was their purpose?

### ISSUE THREAD

**Issue by epictetus-from-hierapolis** [hobinjk/clap-sensor-adapter#4]
Firslty, thank you for sharing the code example. I have followed it in order to implement my own adapter, but there are some questions related to the code that, from my point of vew, doesn't look that will be ever executed.

Here are the lines I'm talking about:

https://github.com/hobinjk/clap-sensor-adapter/blob/792e516e2c72fccad26cb73f9026f44651b4e7a1/clap-sensor-adapter.js#L138
https://github.com/hobinjk/clap-sensor-adapter/blob/792e516e2c72fccad26cb73f9026f44651b4e7a1/clap-sensor-adapter.js#L143
https://github.com/hobinjk/clap-sensor-adapter/blob/792e516e2c72fccad26cb73f9026f44651b4e7a1/clap-sensor-adapter.js#L151
https://github.com/hobinjk/clap-sensor-adapter/blob/792e516e2c72fccad26cb73f9026f44651b4e7a1/clap-sensor-adapter.js#L173

Is there any other updated version which works fully and correctly?

**Comment by hobinjk** [comment]
For a more modern adapter I'd check out https://github.com/mozilla-iot/example-adapter or https://github.com/mozilla-iot/philips-hue-adapter
